name: Frontend CI (Docker)

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/fe-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/fe-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend with Docker
        run: |
          docker build -t washu-frontend-ci:latest ./frontend

      - name: Export build artifacts
        run: |
          id=$(docker create washu-frontend-ci:latest)
          mkdir -p frontend/dist
          docker cp $id:/app/dist ./frontend/dist
          docker rm $id

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
